import clsx from 'clsx'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ThemeProvider } from '@/src/Theme/ThemeProvider'
import Header from '@/src/Theme/feature/layout/Header'
import Footer from '@/src/Theme/feature/layout/Footer'
import { type } from 'os'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
}

type LayoutProps = {
   children: React.ReactNode
   modal?: React.ReactNode
}

export default function RootLayout({
   children, modal
}: LayoutProps ) {
   return (
      <html lang="en">
            <body className={clsx(inter.className, 'bg-background')}>
               <ThemeProvider
                  attribute="class"
                  defaultTheme="system"
                  enableSystem
               >
                  <div className="flex flex-col h-full">
                     <Header />
                     <div className="flex-1 max-w-lg m-auto py-14 w-full">
                        {children}
                     </div>
                     <Footer />
                     
                  {modal}
                  </div>
               </ThemeProvider>
            </body>
        
      </html>
   )
}
